/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchain_templarcoin;

import core.Block;
import core.BlockChain;
import events.EventManager;
import events.RentListener;
import events.NewRwaRegisteredEvent;
import token.TokenRegistry;
import token.TokenRegistryListener;
import rwa.Oracle;
import rwa.RWAExplorer;
import rwa.RWAValidator;
import utils.RMI;

import javax.swing.JOptionPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Painel de Controlo RWA (MyService)
 * Integra a lógica do antigo Main.java com a rede RMI Distributed.
 */
public class MyService extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyService.class.getName());

    // :::::::: COMPONENTES RWA (Do teu projeto antigo) ::::::::
    private BlockChain blockchain;
    private EventManager eventManager;
    private TokenRegistry tokenRegistry;
    private Oracle oracle;
    private RWAValidator validator;
    private RemoteNodeInterface remoteNode; // Conexão RMI

    /**
     * Creates new form MyService
     */
    public MyService() {
        initComponents();
        initRWASystem(); // <--- Inicializa a lógica toda ao arrancar
    }

    /**
     * Método que replica a lógica do antigo Main.java (Steps 4-9)
     */
    private void initRWASystem() {
        try {
            // 1. Inicializar Blockchain Local (necessária para o Explorer e Oracle)
            // Tenta carregar do disco ou cria Genesis
            try {
                System.out.println("A carregar blockchain local...");
                blockchain = BlockChain.load("blockchain.bch");
            } catch (Exception e) {
                // Se falhar, cria uma Blockchain vazia/Genesis temporária
                // Nota: O ideal seria sincronizar com o remoteNode via RMI depois
                Block genesis = new Block(0, new byte[32], 3, List.of("RWA GENESIS"));
                genesis.mine();
                blockchain = new BlockChain(genesis);
                System.out.println("Blockchain nova criada.");
            }

            // 2. Inicializar Gestores de Eventos e Tokens
            eventManager = new EventManager();
            tokenRegistry = new TokenRegistry();
            
            // Subscrever Listeners
            eventManager.subscribe(new TokenRegistryListener(tokenRegistry));
            eventManager.subscribe(new RentListener(tokenRegistry)); // O RentListener atualiza saldos

            // 3. Inicializar Oracle e Validator
            oracle = new Oracle(blockchain, eventManager);
            validator = new RWAValidator();

            System.out.println("Sistema RWA Inicializado com Sucesso!");

        } catch (Exception e) {
            System.err.println("Erro ao iniciar sistema RWA: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtNodeAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanelRWA = new javax.swing.JPanel();
        btOpenExplorer = new javax.swing.JButton();
        btConnect = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RWA Service Dashboard");

        txtNodeAddress.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtNodeAddress.setText("//localhost:10010/remoteP2P");
        txtNodeAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Remote Object Address (RMI)"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestão RWA & Blockchain");

        jPanelRWA.setBorder(javax.swing.BorderFactory.createTitledBorder("RWA Menu"));

        btOpenExplorer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btOpenExplorer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/transaction.png"))); // NOI18N
        btOpenExplorer.setText("Abrir RWA Explorer (Menu)");
        btOpenExplorer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenExplorerActionPerformed(evt);
            }
        });

        btConnect.setText("Conectar à Rede");
        btConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnectActionPerformed(evt);
            }
        });

        lblStatus.setText("Status: Offline");

        javax.swing.GroupLayout jPanelRWALayout = new javax.swing.GroupLayout(jPanelRWA);
        jPanelRWA.setLayout(jPanelRWALayout);
        jPanelRWALayout.setHorizontalGroup(
            jPanelRWALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRWALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRWALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btOpenExplorer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelRWALayout.createSequentialGroup()
                        .addComponent(btConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRWALayout.setVerticalGroup(
            jPanelRWALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRWALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRWALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addComponent(btOpenExplorer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRWA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNodeAddress)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNodeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelRWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    // 1. CONECTAR À REDE RMI (Substitui o conectar por Socket do Main antigo)
    private void btConnectActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            String address = txtNodeAddress.getText();
            remoteNode = (RemoteNodeInterface) RMI.getRemote(address);
            lblStatus.setText("Status: Conectado a " + address);
            
            // Aqui podias sincronizar a blockchain local com a remota
            // List<String> transactions = remoteNode.getTransactions();
            // blockchain.sync(transactions); // (Pseudocódigo)
            
        } catch (Exception ex) {
            lblStatus.setText("Status: Erro de conexão");
            logger.log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Não foi possível conectar ao nó remoto.");
        } 
    }                                         

    // 2. ABRIR O RWA EXPLORER (O Menu Antigo)
    private void btOpenExplorerActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if (blockchain == null) {
            JOptionPane.showMessageDialog(this, "Erro: Blockchain não inicializada.");
            return;
        }

        try {
            System.out.println("A iniciar RWA Explorer...");
            
            // Criar o Explorer passando as dependências locais
            RWAExplorer explorer = new RWAExplorer(blockchain, oracle, validator);
            
            // INJEÇÃO DE DEPENDÊNCIAS EXTRA
            explorer.setRegistry(tokenRegistry); 
            
            // IMPORTANTE: O Explorer antigo esperava um P2PNode para enviar mensagens.
            // Como agora usamos RMI, terás de adaptar o Explorer para usar o 'remoteNode'
            // ou criar um adaptador. Por agora, ele vai abrir e ler a blockchain local.
            
            explorer.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir Explorer: " + e.getMessage());
            e.printStackTrace();
        }
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new MyService().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btConnect;
    private javax.swing.JButton btOpenExplorer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelRWA;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtNodeAddress;
    // End of variables declaration                   
}